[tool.poetry]
name = "studypython"
version = "0.1.0"
description = ""
authors = ["Anas Hagras <anas.elsayed@bld.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
